In [2]:
import pandas as  pd
df = pd.read_csv('salaries_by_college_major.csv')
df.head()

     Undergraduate Major  ...     Group
0             Accounting  ...  Business
1  Aerospace Engineering  ...      STEM
2            Agriculture  ...  Business
3           Anthropology  ...      HASS
4           Architecture  ...  Business

[5 rows x 6 columns]

In [3]:
df.shape

(51, 6)

In [4]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [5]:
df.isna()

    Undergraduate Major  ...  Group
0                 False  ...  False
1                 False  ...  False
2                 False  ...  False
3                 False  ...  False
4                 False  ...  False
5                 False  ...  False
6                 False  ...  False
7                 False  ...  False
8                 False  ...  False
9                 False  ...  False
10                False  ...  False
11                False  ...  False
12                False  ...  False
13                False  ...  False
14                False  ...  False
15                False  ...  False
16                False  ...  False
17                False  ...  False
18                False  ...  False
19                False  ...  False
20                False  ...  False
21                False  ...  False
22                False  ...  False
23                False  ...  False
24                False  ...  False
25                False  ...  False
26                False  ...  False
27                False  ...  False
28                False  ...  False
29                False  ...  False
30                False  ...  False
31                False  ...  False
32                False  ...  False
33                False  ...  False
34                False  ...  False
35                False  ...  False
36                False  ...  False
37                False  ...  False
38                False  ...  False
39                False  ...  False
40                False  ...  False
41                False  ...  False
42                False  ...  False
43                False  ...  False
44                False  ...  False
45                False  ...  False
46                False  ...  False
47                False  ...  False
48                False  ...  False
49                False  ...  False
50                False  ...   True

[51 rows x 6 columns]

In [6]:
df.tail()

      Undergraduate Major  ...  Group
46             Psychology  ...   HASS
47               Religion  ...   HASS
48              Sociology  ...   HASS
49                Spanish  ...   HASS
50  Source: PayScale Inc.  ...    NaN

[5 rows x 6 columns]

In [7]:
clean_df = df.dropna()
cleandf.tail()

NameError: ignored

In [8]:
clean_df.tail()

   Undergraduate Major  ...  Group
45   Political Science  ...   HASS
46          Psychology  ...   HASS
47            Religion  ...   HASS
48           Sociology  ...   HASS
49             Spanish  ...   HASS

[5 rows x 6 columns]

In [9]:
clean_df['Starting Median Salary'].max()

74300.0

In [12]:
clean_df['Starting Median Salary'].idxmax()

43

In [13]:
clean_df['Undergraduate Major'].loc[43]

'Physician Assistant'

In [14]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

In [15]:
clean_df

                     Undergraduate Major  ...     Group
0                             Accounting  ...  Business
1                  Aerospace Engineering  ...      STEM
2                            Agriculture  ...  Business
3                           Anthropology  ...      HASS
4                           Architecture  ...  Business
5                            Art History  ...      HASS
6                                Biology  ...      STEM
7                    Business Management  ...  Business
8                   Chemical Engineering  ...      STEM
9                              Chemistry  ...      STEM
10                     Civil Engineering  ...      STEM
11                        Communications  ...      HASS
12                  Computer Engineering  ...      STEM
13                      Computer Science  ...      STEM
14                          Construction  ...  Business
15                      Criminal Justice  ...      HASS
16                                 Drama  ...      HASS
17                             Economics  ...  Business
18                             Education  ...      HASS
19                Electrical Engineering  ...      STEM
20                               English  ...      HASS
21                                  Film  ...      HASS
22                               Finance  ...  Business
23                              Forestry  ...  Business
24                             Geography  ...      HASS
25                               Geology  ...      STEM
26                        Graphic Design  ...      HASS
27            Health Care Administration  ...  Business
28                               History  ...      HASS
29                 Hospitality & Tourism  ...  Business
30                Industrial Engineering  ...      STEM
31           Information Technology (IT)  ...      STEM
32                       Interior Design  ...      HASS
33               International Relations  ...      HASS
34                            Journalism  ...      HASS
35  Management Information Systems (MIS)  ...      STEM
36                             Marketing  ...  Business
37                                  Math  ...      STEM
38                Mechanical Engineering  ...      STEM
39                                 Music  ...      HASS
40                               Nursing  ...  Business
41                             Nutrition  ...      HASS
42                            Philosophy  ...      HASS
43                   Physician Assistant  ...      STEM
44                               Physics  ...      STEM
45                     Political Science  ...      HASS
46                            Psychology  ...      HASS
47                              Religion  ...      HASS
48                             Sociology  ...      HASS
49                               Spanish  ...      HASS

[50 rows x 6 columns]

In [16]:
clean_df['Mid-Career Median Salary'].idxmax()

8

In [17]:
clean_df.loc[8]

Undergraduate Major                  Chemical Engineering
Starting Median Salary                            63200.0
Mid-Career Median Salary                         107000.0
Mid-Career 10th Percentile Salary                 71900.0
Mid-Career 90th Percentile Salary                194000.0
Group                                                STEM
Name: 8, dtype: object

In [18]:
clean_df['Starting Median Salary'].idxmin()

49

In [19]:
clean_df.loc[49]

Undergraduate Major                  Spanish
Starting Median Salary               34000.0
Mid-Career Median Salary             53100.0
Mid-Career 10th Percentile Salary    31000.0
Mid-Career 90th Percentile Salary    96400.0
Group                                   HASS
Name: 49, dtype: object

In [20]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [21]:
spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']
clean_df.insert(1,'Spread', spread_col)
clean_df.head()

     Undergraduate Major    Spread  ...  Mid-Career 90th Percentile Salary     Group
0             Accounting  109800.0  ...                           152000.0  Business
1  Aerospace Engineering   96700.0  ...                           161000.0      STEM
2            Agriculture  113700.0  ...                           150000.0  Business
3           Anthropology  104200.0  ...                           138000.0      HASS
4           Architecture   85400.0  ...                           136000.0  Business

[5 rows x 7 columns]

In [22]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major   Spread
40                     Nursing  50700.0
43         Physician Assistant  57600.0
41                   Nutrition  65300.0
49                     Spanish  65400.0
27  Health Care Administration  66400.0

In [23]:
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [24]:
greatest_spread = clean_df.sort_values('Spread', ascending=False)
greatest_spread[['Undergraduate Major', 'Spread']].head()

   Undergraduate Major    Spread
17           Economics  159400.0
22             Finance  147800.0
37                Math  137800.0
36           Marketing  132900.0
42          Philosophy  132500.0

In [25]:
clean_df.groupby('Group').count()

          Undergraduate Major  ...  Mid-Career 90th Percentile Salary
Group                          ...
Business                   12  ...                                 12
HASS                       22  ...                                 22
STEM                       16  ...                                 16

[3 rows x 6 columns]

In [26]:
clean_df.groupby('Group').mean()

                 Spread  ...  Mid-Career 90th Percentile Salary
Group                    ...
Business  103958.333333  ...                      147525.000000
HASS       95218.181818  ...                      129363.636364
STEM      101600.000000  ...                      157625.000000

[3 rows x 5 columns]

In [27]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby('Group').mean()

             Spread  ...  Mid-Career 90th Percentile Salary
Group                ...
Business 103,958.33  ...                         147,525.00
HASS      95,218.18  ...                         129,363.64
STEM     101,600.00  ...                         157,625.00

[3 rows x 5 columns]